Autoprune [1/6]
enzingerm/snapborg pull request #7
Opened 2021-10-29 10:20 UTC by jrabinow

Snapborg autoprunes after backing up latest batch of snapshots.

Use the `--no-prune` flag to disable this behavior.

2021-10-30 13:09 UTC, enzingerm requested changes
Thanks for the PR and very nice to have autopruning in one command! The only thing which makes me a bit uncomfortable is the implicit invocation of `prune` if no argument is given. We have commands `backup` and `prune`, so it is a bit weird to have `backup` implicitly also run `prune`. I would like the idea of inverting the switch and call it `--prune`, which would be disabled by default.

2021-10-30 22:34 UTC, jrabinow commented
I see snapborg as eventually having the exact same interface as borgmatic, and as such I tried to stay as close to borgmatic's user experience as possible. Running a few tests, I found that borgmatic auto-prunes by default - creation without pruning is not the default behavior.
I can see why they did things that way: users have to specify a retention policy, the tool may as well act on it. Why make users remember to run 2 commands when a single command works?

I'd like to make sure you know about these arguments. If they aren't enough to convince you, I'll switch things around to how you requested.

2021-11-01 15:04 UTC, enzingerm commented
Even if `borg prune` is not invoked, snapborg already acts on the specified retention policy during backup: it uses it to calculate which snapper snapshots it should choose to actually back up. This is not that relevant when snapborg is run periodically in a short interval, because it will transfer the most recent snapshot(s) (older snapshots would already have been transferred by an earlier invocation of snapborg). However, in my original use case the backup target (ext. HDD) might not be accessible permanently and  I wanted snapborg to also transfer one snapshot for all the previous days if the HDD was plugged in from time to time. This is also the reason for the "fault tolerant mode" which can be activated in the config.

One can now argue why snapborg uses its own retention policy and does not leave the task of thinning out the snapshots to snapper itself and its timeline cleanup algorithm. But my thought was that I would like to have more "dense" snapshots on the live machine and only transfer a subset of those to the borg repository. And I wanted to have older snapshots in the borg repo which don't need to be kept on the live machine.

Coming back to this PR, I understand the point and as snapborg is already more than just a simple wrapper around borg (it acts on multiple configs/repos and snapshots at once), it is already quite close to borgmatic. So yes, let's leave the switch as you suggested. But please mention it in the README in the Usage section as a parameter to the `backup` subcommand.

2021-11-03 02:27 UTC, jrabinow commented
It sounds like we have a very similar setup/usecase.

Good catch with the README, I've updated it too.

2021-11-04 20:17 UTC, enzingerm commented
About the PKGBUILD, I don't think there is a userbase yet which could be caught off-guard by this. And even so, pruning is something you would want to do once in a while anyways.

Concerning the Borgmatic like interface, this would be for sure a cool thing, especially for things like hooks or automatic consistency checks. But this is also not something which I would want to implement by myself, as the tool already does what I want it to do. The corresponding issue can stay open and if someone feels motivated, he can do it.

2021-11-04 20:19 UTC, enzingerm commented on README.md
> +                    and then created from scratch
I suppose this line shouldn't belong here :)

2021-11-04 21:02 UTC, jrabinow commented on README.md
> +                    and then created from scratch
Indeed 😁 fixed!

2021-11-05 08:48 UTC, merged